services:
  redis-container:
    container_name: redis-container
    image: docker.io/redis:7.2.3
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    networks:
      - app-network
  spring-container:
    container_name: spring-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      REDIS_HOST: redis-container
      REDIS_PORT: 6379
      KAFKA_BROKER_SERVER: kafka-broker-01
      KAFKA_BROKER_PORT: 19092
      RECOMMEND_API_HOST: recommend-system
      RECOMMEND_API_PORT: 3000
    networks:
      - app-network

  recommend-system:
    container_name: recommend-system
    image: hoanganh1511/recommend-system:1.3
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge